### 1. 필요한 라이브러리

In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
import time

### 2. 셀레니움 활용 웹브라우저 자동화

In [2]:
# # 웹드라이버 불러오는 함수 (주의: 기본 설정있음)
# def makeWebdriver(driver_loc):
#     from selenium import webdriver
#     driver_loc = driver_loc
#     options = webdriver.ChromeOptions()
#     options.add_argument('window-size=1920*1080')
#     #헤드리스 설정 시 리눅스 같이 웹화면 없는경우에도 웹페이지 실행가능함
#     options.add_argument('headless')
#     options.add_argument("disablegpu")
#     driver = webdriver.Chrome(driver_loc, options=options)
#     driver.maximize_window
#     return driver

# driver = makeWebdriver("C:/Program Files/Google/Chrome/Application/chromedriver.exe")

#### - 라이브러리 선언 및 드라이버 설정

In [3]:
# 라이브러리 선언
from selenium import webdriver
from bs4 import BeautifulSoup

# 드라이버 위치 설정
driver_loc = "C:/Program Files/Google/Chrome/Application/chromedriver.exe"

# 드라이버 옵션 설정
options = webdriver.ChromeOptions()
#헤드리스 설정 시 리눅스 같이 웹화면 없는경우에도 웹페이지 실행가능함
# options.add_argument('headless')
# options.add_argument("window-size=1920*1080")
# options.add_argument('disable-gpu')

options.add_argument('--headless')
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

# 웹드라이버 정의
driver = webdriver.Chrome(driver_loc, options=options)

#### - 웹페이지 이동 (기업현황)

In [4]:
# url 정의
baseUrl = "https://navercomp.wisereport.co.kr/v2/company/c1010001.aspx?cmp_cd=041830&cn="

# url 이동
driver.get(baseUrl)

# 현재 url 정보
# driver.current_url

In [5]:
com_response = driver.page_source 
bs_com = BeautifulSoup(com_response, "html.parser")
# bs

In [6]:
cols = bs_com.find_all("tbody")[12].find_all("th")

title = [col.text.replace("\xa0","") for col in cols]
# title

In [7]:
def strToFloat(x):
    return float(x.replace(',',''))

In [8]:
# [strToFloat(x) for x in row]

In [9]:
trs = bs_com.find_all("tbody")[12].find_all("tr")
tr_cnt = len(trs)


data = []

for i in range(tr_cnt):
    row = []
    tds = trs[i].find_all("td")
    row = [value.text.replace(',','') for index, value in enumerate(tds) if index < 4]
    data.append(row)
data

[['933', '996', '1171', ''],
 ['249', '237', '276', ''],
 ['249', '237', '276', ''],
 ['234', '246', '282', ''],
 ['193', '196', '204', ''],
 ['193', '197', '204', ''],
 ['0', '-1', '0', ''],
 ['1120', '1317', '1549', ''],
 ['55', '72', '151', ''],
 ['1065', '1245', '1398', ''],
 ['1065', '1244', '1397', ''],
 ['0', '', '', ''],
 ['68', '68', '68', ''],
 ['186', '177', '242', ''],
 ['-131', '-177', '-120', ''],
 ['-42', '-17', '-74', ''],
 ['53', '409', '31', ''],
 ['133', '-232', '211', ''],
 ['0', '0', '0', ''],
 ['26.70', '23.76', '23.60', ''],
 ['20.73', '19.62', '17.43', ''],
 ['19.44', '17.04', '15.47', ''],
 ['18.49', '16.05', '14.24', ''],
 ['5.17', '5.74', '10.78', ''],
 ['1517.09', '1780.94', '2053.85', ''],
 ['1412', '1438', '1493', ''],
 ['28.40', '15.10', '15.84', ''],
 ['7897', '9241', '10502', ''],
 ['5.08', '2.35', '2.25', ''],
 ['120', '120', '140', ''],
 ['0.30', '0.55', '0.59', ''],
 ['8.37', '8.22', '9.12', ''],
 ['13683782', '13683782', '13683782', '']]

In [10]:
list(map(strToFloat, row[:3]))

[13683782.0, 13683782.0, 13683782.0]

In [11]:
finSummary = pd.DataFrame(data, index=title)
finSummary

                   0         1         2 3
매출액              933       996      1171
영업이익             249       237       276
영업이익(발표기준)       249       237       276
세전계속사업이익         234       246       282
당기순이익            193       196       204
당기순이익(지배)        193       197       204
당기순이익(비지배)         0        -1         0
자산총계            1120      1317      1549
부채총계              55        72       151
자본총계            1065      1245      1398
자본총계(지배)        1065      1244      1397
자본총계(비지배)          0
자본금               68        68        68
영업활동현금흐름         186       177       242
투자활동현금흐름        -131      -177      -120
재무활동현금흐름         -42       -17       -74
CAPEX             53       409        31
FCF              133      -232       211
이자발생부채             0         0         0
영업이익률          26.70     23.76     23.60
순이익률           20.73     19.62     17.43
ROE(%)         19.44     17.04     15.47
ROA(%)         18.49     16.05     14.24
부채비율            5.17      5.74     10.78
자본유보율        1517.09   1780.94   2053.85
EPS(원)          1412      1438      1493
PER(배)         28.40     15.10     15.84
BPS(원)          7897      9241     10502
PBR(배)          5.08      2.35      2.25
현금DPS(원)         120       120       140
현금배당수익률         0.30      0.55      0.59
현금배당성향(%)       8.37      8.22      9.12
발행주식수(보통주)  13683782  13683782  13683782

In [12]:
type(finSummary.iloc[0,0])

str

#### - 웹페이지 이동 (재무분석)

In [13]:
# url 정의
baseUrl = "https://navercomp.wisereport.co.kr/v2/company/c1030001.aspx?cmp_cd=041830&cn="

# url 이동
driver.get(baseUrl)

# 현재 url 정보
# driver.current_url

In [14]:
quizBtnXpath = '//*[@id="rpt_tab2"]'
driver.find_element_by_xpath(quizBtnXpath).click()
time.sleep(1)

In [15]:
response = driver.page_source 
# response

In [16]:
bs_fin = BeautifulSoup(response, "html.parser")
# bs
# 1
# 126
# 127
# 248
# 243
# 89
# 228

In [17]:
trs = bs_fin.find_all("tbody")[5].find_all("tr")
trs[228]

list = [value for index, value in enumerate(trs) if index in [1, 126, 127, 248, 243, 89, 228]]
list[0].find("td").text.replace("\n","").replace("\t","").replace("\xa0","")
list[0].find_all("td")[5].text

len(list)

# for i in range(len(list)):
#     title = [value for value in list[i]]
#     title = list[i].find("td").text.replace("\n","").replace("\t","").replace("\xa0","")

index = [title.find("td").text.replace("\n","").replace("\t","").replace("\xa0","").replace("*","").replace("펼치기","") for title in list]
index

list

data = []

for i in range(len(list)):
    row = []
    tds = list[i].find_all("td")
    row = [value.text.replace(',','') for index, value in enumerate(tds) if index in [1, 2, 3, 4, 5]]
    data.append(row)
    
data

[['541.3', '643.4', '751.3', '555.1', '740.4'],
 ['34.1', '26.8', '30.5', '31.5', '25.0'],
 ['61.1', '47.3', '55.1', '71.5', '150.7'],
 ['59.3', '41.1', '49.8', '59.2', '108.5'],
 ['-2.6', '-2.6', '-31.1', '-33.7', '-71.1'],
 ['173.1', '169.9', '193.2', '196.7', '204.3'],
 ['13684', '13684', '13684', '13684', '13684']]

In [18]:
finStatements = pd.DataFrame(data, index=index)
finStatements

               0      1      2      3      4
유동자산       541.3  643.4  751.3  555.1  740.4
투자자산        34.1   26.8   30.5   31.5   25.0
부채총계        61.1   47.3   55.1   71.5  150.7
유동부채        59.3   41.1   49.8   59.2  108.5
자기주식        -2.6   -2.6  -31.1  -33.7  -71.1
(지배)당기순이익  173.1  169.9  193.2  196.7  204.3
발행주식수      13684  13684  13684  13684  13684

In [19]:
finSummary

                   0         1         2 3
매출액              933       996      1171
영업이익             249       237       276
영업이익(발표기준)       249       237       276
세전계속사업이익         234       246       282
당기순이익            193       196       204
당기순이익(지배)        193       197       204
당기순이익(비지배)         0        -1         0
자산총계            1120      1317      1549
부채총계              55        72       151
자본총계            1065      1245      1398
자본총계(지배)        1065      1244      1397
자본총계(비지배)          0
자본금               68        68        68
영업활동현금흐름         186       177       242
투자활동현금흐름        -131      -177      -120
재무활동현금흐름         -42       -17       -74
CAPEX             53       409        31
FCF              133      -232       211
이자발생부채             0         0         0
영업이익률          26.70     23.76     23.60
순이익률           20.73     19.62     17.43
ROE(%)         19.44     17.04     15.47
ROA(%)         18.49     16.05     14.24
부채비율            5.17      5.74     10.78
자본유보율        1517.09   1780.94   2053.85
EPS(원)          1412      1438      1493
PER(배)         28.40     15.10     15.84
BPS(원)          7897      9241     10502
PBR(배)          5.08      2.35      2.25
현금DPS(원)         120       120       140
현금배당수익률         0.30      0.55      0.59
현금배당성향(%)       8.37      8.22      9.12
발행주식수(보통주)  13683782  13683782  13683782

### 4-1. EPS * PER 함수

In [25]:
def eps_per(finSummary):
    if finSummary[3]['EPS(원)'] == '':
        pre_eps = float(finSummary[1]['EPS(원)'])
        now_eps = float(finSummary[2]['EPS(원)'])
        eps = (pre_eps + now_eps / 2)
        per = (float(finSummary[0]['PER(배)']) + float(finSummary[1]['PER(배)']) + float(finSummary[2]['PER(배)'])) / 3
        eps_per = eps * per
    else:
        pre_eps = float(finSummary[2]['EPS(원)'])
        now_eps = float(finSummary[3]['EPS(원)'])
        eps = (pre_eps + now_eps / 2)
        per = (float(finSummary[0]['PER(배)']) + float(finSummary[1]['PER(배)']) + float(finSummary[2]['PER(배)']) + float(finSummary[3]['PER(배)'])) / 4
        eps_per = eps * per
    return eps_per

In [26]:
eps_per(finSummary)

43209.41

### 4-2. 현명한 투자자 함수

In [18]:
def investor(df):
    tax_rate = 25
    expected_rate = 7.9
    business_val = (float(df[2]['영업이익'].replace(',','')) + float(df[3]['영업이익'].replace(',','')) + float(df[4]['영업이익'].replace(',',''))) * ((100 - tax_rate)/ expected_rate)
    # investor_val = (business_val + (유동자산-(유동부채*1.2)+투자자산) - 고정부채) / 발행주식수 * 10^8
    return investor_val